[package]
name = "worm"
version = "0.1.0"
edition = "2021"

[features]
derive = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
worm_core = { path = "./worm_core" }
worm_derive = { path = "./worm_derive" }
